
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
    - id: check-added-large-files
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-merge-conflict
    - id: fix-encoding-pragma
      args: ["--remove"]
    - id: mixed-line-ending
      args: ["--fix=lf"]

# Golang hooks
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-lint
    - id: go-imports
    - id: go-cyclo
      args: [-over=15]
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
    - id: go-mod-tidy
