name: Commit Stage
run-name: Commit Stage - ${{ github.ref }}

on:
  push:
    branches:
      - '*'
      - '!main'
  workflow_call:
    # Allows for workflow reusability

# Avoids running the same workflow concurrently on the same branch
concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build Application
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Project + Cache Setup ------------------------------- #
      - name: Set up Go 1.22.0
        id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
          cache-dependency-path: src/go.sum

      - name: Set up cache
        id: setup-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-${{ hashFiles('**/go.sum') }}
            go-

      - name: Install dependencies
        id: install-dependencies
        run: |
          cd src
          go build

  test:
    runs-on: ubuntu-22.04
    needs: build
    name: Unit Test
    steps:
      - uses: actions/checkout@v4

      # ------------------------------- Unit Tests ------------------------------- #
      - name: Restore cache from the build stage
        id: restore-cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.cache/go-build
          key: go-${{ hashFiles('**/requirements.txt') }}

      - name: Install cached dependencies
        id: restore-dependencies
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: |
          cd src
          go build

      - name: Unit Testing with Golang testing package
        id: unit_test
        run: |
          cd src
          go test ./...
